version: "3.8"
services:
  tmodloader:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tmodloader
    ports:
      - 7777:7777
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    volumes:
      - ./data:/root/.local/share/Terraria/tModLoader
